language: node_js
node_js:
 - "node"
services:
  - postgresql
before_script:
  - psql -c 'create database curious_test;' -U postgres
  - npm run createDb
  - npm run build

after_success:
  - npm run test
